// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNhd8ss1K87QV-R6BlvLREQnk10UhZ_E',
    appId: '1:1079270040096:web:02a61699781c7e56d91245',
    messagingSenderId: '1079270040096',
    projectId: 'takeit-821b3',
    authDomain: 'takeit-821b3.firebaseapp.com',
    storageBucket: 'takeit-821b3.appspot.com',
    measurementId: 'G-K7NQYV70V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_EZM5DaWzG7oZXxF5TLbp9OX9PkVADrM',
    appId: '1:1079270040096:android:e04a29d3795869e1d91245',
    messagingSenderId: '1079270040096',
    projectId: 'takeit-821b3',
    storageBucket: 'takeit-821b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1eQgt_4xygCm8dU8dxgG6OE9BzmG3fRo',
    appId: '1:1079270040096:ios:321af370c52f4394d91245',
    messagingSenderId: '1079270040096',
    projectId: 'takeit-821b3',
    storageBucket: 'takeit-821b3.appspot.com',
    iosClientId: '1079270040096-04roiuantsrc19dglbm4t3k3p2bueubt.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
