final List<Map<String, String>> cities = [
  {"country": "Egypt", "city": "Cairo"},
  {"country": "Egypt", "city": "Alexandria"},
  {"country": "Egypt", "city": "Giza"},
  {"country": "Egypt", "city": "Shubra elKhema"},
  {"country": "Egypt", "city": "Port Said"},
  {"country": "Egypt", "city": "Suez"},
  {"country": "Egypt", "city": "ElMahalla elKubra"},
  {"country": "Egypt", "city": "ElMansoura"},
  {"country": "Egypt", "city": "Tanta"},
  {"country": "Egypt", "city": "Asyut"},
  {"country": "Egypt", "city": "Fayoum"},
  {"country": "Egypt", "city": "Zagazig"},
  {"country": "Egypt", "city": "Ismailia"},
  {"country": "Egypt", "city": "Khusus"},
  {"country": "Egypt", "city": "Aswan"},
  {"country": "Egypt", "city": "Damanhur"},
  {"country": "Egypt", "city": "ElMinya"},
  {"country": "Egypt", "city": "Damietta"},
  {"country": "Egypt", "city": "Luxor"},
  {"country": "Egypt", "city": "Qena"},
  {"country": "Egypt", "city": "Beni Suef"},
  {"country": "Egypt", "city": "Sohag"},
  {"country": "Egypt", "city": "Shibin elKom"},
  {"country": "Egypt", "city": "Hurghada"},
  {"country": "Egypt", "city": "Banha"},
  {"country": "Egypt", "city": "Kafr alSheikh"},
  {"country": "Egypt", "city": "Mallawi"},
  {"country": "Egypt", "city": "El Arish"},
  {"country": "Egypt", "city": "Belbeis"},
  {"country": "Egypt", "city": "10th of Ramadan"},
  {"country": "Egypt", "city": "Marsa Matruh"},
  {"country": "Egypt", "city": "Mit Ghamr"},
  {"country": "Egypt", "city": "Kafr elDawwar"},
  {"country": "Egypt", "city": "Qalyub"},
  {"country": "Egypt", "city": "Desouk"},
  {"country": "Egypt", "city": "Abu Kabir"},
  {"country": "Germany", "city": "Berlin"},
  {"country": "Germany", "city": "Hanover"},
  {"country": "Germany", "city": "Munich"},
  {"country": "Germany", "city": "Hamburg"},
  {"country": "Germany", "city": "Düsseldorf"},
  {"country": "Germany", "city": "Stuttgart"},
];
